config/routes.rb
RamusVykaz::Application.routes.draw do
  resources :prace_polozkas
  match '/statistika', to: 'prace_polozkas#statistika', via: 'get'
  match '/settings', to: 'prace_polozkas#settings', via: 'get'
  match '/settings', to: 'prace_polozkas#settings', via: 'post'

  match '/month_statistika', to: 'prace_polozkas#month_statistika', via: 'get'

  resources :osobas

  resources :projekts
  match '/projekts/new', to: 'projekts#new', via: 'post'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root 'prace_polozkas#index'

end

app/models/prace_polozka.rb
class PracePolozka < ActiveRecord::Base
  belongs_to :osoba
  belongs_to :projekt
  accepts_nested_attributes_for :osoba, :allow_destroy => true, :reject_if => proc { |obj| obj.blank? }
  accepts_nested_attributes_for :projekt, :allow_destroy => true, :reject_if => proc { |obj| obj.blank? }
  validates :hodiny, :numericality => { :greater_than_or_equal_to => 0}
  # validates :projekt_id, presence: true

end

app/controllers/prace_polozkas_controller.rb
class PracePolozkasController < ApplicationController
  before_action :set_prace_polozka, only: [:show, :edit, :update, :destroy]
  # GET /prace_polozkas
  # GET /prace_polozkas.json
  def index
    @prace_polozkas = PracePolozka.all
    if signed_in?
      @aktualni_hodiny = PracePolozka.where(osoba_id: current_user.osoba_id).sum('hodiny')
    end
  end

  def settings
    @osobas = Osoba.all
    @projekts = Projekt.all
    @users = User.all

    if request.post?

      direction = params['direction']

      if params.key?('user_id')
        userid = params['user_id']
        u = User.find_by(id: userid)
        u.update_attribute(:active, direction)
      end

      if params.key?('project_id')
        projectid = params['project_id']
        pr = Projekt.find_by(id: projectid)
        pr.update_attribute(:active, direction)
      end

    end
  end

  def statistika

    def get_projekt_nazev(projekt_id)
      return "banana"
    end

    @prace_polozkas = PracePolozka.all
    @projekts = Projekt.all
    @osobas = Osoba.all

    @mesicni_hodiny = []
    @osobas.each do |os|
      if User.find_by(id: os.id).active
        @mesicni_hodiny << [os.id, os.prijmeni, os, os.prace_polozkas.group("date_trunc('month', datum)").sum('hodiny')]
      end
    end

    @mesicni_hodiny = @mesicni_hodiny.sort_by { |_a, b| b }
    @projektove_hodiny = []
    @projekts.each do |pr|
      @projektove_hodiny << [pr.id, pr, pr.prace_polozkas.group("date_trunc('month',datum)").sum('hodiny')]
    end

    @months_worked = {}
    @months_worked_osobas = {}
    months_worked = @prace_polozkas.map { |pp| [pp.datum.month, pp.datum.year].join(' ') }.uniq
    # byebug
    months_worked.each do |month|
      res = @prace_polozkas.select do |pp|
        [pp[:datum].month, pp[:datum].year].join(' ') == month
      end
      sum_by_project = res.group_by(&:projekt_id).map { |x, y| [x, y.inject(0) { |sum, i| sum + i.hodiny }] }
      sum_by_project = sum_by_project.sort_by { |a| a[0] }

      # res jsou pracepolozky v tomto mesici
      # chci je sgrupovat podle lidi, ale pak je rozdelit.
      # krok 1 sgrupovat podle lidi

      # sum_by_osoba vraci:
      # [[8, 14.0, [[3, 2.0], [8, 10.5], [5, 0.5], [20, 1.0]]], [5, 20.5, [[5, 5.0], [8, 9.0], [2, 6.5]]], .... ]
      #  tj. pro dany mesic:
      # [[osoba_id, hodiny za mesic soucet, [[projekt_id, hodiny], [projekt_id, hodiny], ...]], [osoba_id, hodiny za mesic soucet, [[projekt_id, hodiny], [projekt_id, hodiny], ...]], .... ]


      sum_by_osoba = res.group_by(&:osoba_id).map { |x, y| [x, y.inject(0) { |sum, i| sum + i.hodiny },y.group_by(&:projekt_id).map { |proj, hod| [proj, hod.inject(0) { |souc, et| souc + et.hodiny} ]}.sort_by { |a| a[0]} ] }
      sum_by_osoba = sum_by_osoba.sort_by { |a| a[0] }

      # byebug

      @months_worked[month] = sum_by_project
      @months_worked_osobas[month] = sum_by_osoba
    end

    # byebug

    # projekty_po_mesici_dle_cloveka = Osoba.all.product([1]).to_h
    # projekty_po_mesici_dle_cloveka.each do |os|
    # mesicni_projektove_hodiny = Osoba.all.product([1]).to_h

    @mesicni_projektove_hodiny = {}
    @osobas.each do |os|
      @mesicni_projektove_hodiny[os.id] = [os.prace_polozkas]
    end
  end

  def month_statistika
    @prace_polozkas = PracePolozka.all
    @projekts = Projekt.all
    @osobas = Osoba.all
    @mesicni_hodiny = []
    @osobas.each do |os|
      @mesicni_hodiny << [os.id, os, os.prace_polozkas.group("date_trunc('month', datum)").sum('hodiny')]
    end
    # @range = (1.year.ago.to_date..DateTime.now.to_date).to_s
    # @unfinished_range = (1.year.ago.to_date..DateTime.now.to_date).group_by(&:month).map { |_,v| (v.first.month.to_s + "/" + v.first.year.to_s) }
  end

  # GET /prace_polozkas/1
  # GET /prace_polozkas/1.json
  def show
  end

  # GET /prace_polozkas/new
  def new
    @prace_polozka = PracePolozka.new
    projektsort
    # projektchart
    @active_projekts = Projekt.where(active: true).collect {|p| [p.nazev, p.id]}.sort
  end

  # GET /prace_polozkas/1/edit
  def edit
    projektsort
    # projektchart
    @active_projekts = Projekt.where(active: true).collect {|p| [p.nazev, p.id]}.sort
    @osobas = Osoba.all.collect {|p| [p.jmeno.to_s + " " + p.prijmeni.to_s, p.id]}.sort
  end

  # POST /prace_polozkas
  # POST /prace_polozkas.json
  def create
    @prace_polozka = PracePolozka.new(prace_polozka_params)

    respond_to do |format|
      if @prace_polozka.save
        format.html { redirect_to action: 'index' } # changed to render index from redirect_to @prace_polozka
        format.json { render action: 'show', status: :created, location: @prace_polozka }
        flash[:notice] = "Záznam byl vytvořen!"
      else
        format.html { render action: 'new' }
        format.json { render json: @prace_polozka.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prace_polozkas/1
  # PATCH/PUT /prace_polozkas/1.json
  def update
    respond_to do |format|
      if @prace_polozka.update(prace_polozka_params)
        format.html { redirect_to action: 'index', notice: 'Zaznam byl zmenen.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @prace_polozka.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prace_polozkas/1
  # DELETE /prace_polozkas/1.json
  def destroy
    @prace_polozka.destroy
    respond_to do |format|
      format.html { redirect_to prace_polozkas_url }
      format.json { head :no_content }
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_prace_polozka
    @prace_polozka = PracePolozka.find(params[:id])
  end

  def projektsort
    @projekts = Projekt.all.collect {|p| [p.nazev, p.id]}.sort
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def prace_polozka_params
    params.require(:prace_polozka).permit(:osoba_id, :projekt_id, :datum, :obsah, :hodiny)
  end

  def projektchart
        # Org chart
        data_table1 = GoogleVisualr::DataTable.new
        data_table2 = GoogleVisualr::DataTable.new
        data_table3 = GoogleVisualr::DataTable.new
        data_table4 = GoogleVisualr::DataTable.new
    # Add Column Headers
    data_table1.new_column('string', 'Nazev a kod')
    data_table1.new_column('string', 'Rodic')
    data_table1.new_column('string', 'Tooltip')
    data_table2.new_column('string', 'Nazev a kod')
    data_table2.new_column('string', 'Rodic')
    data_table2.new_column('string', 'Tooltip')
    data_table3.new_column('string', 'Nazev a kod')
    data_table3.new_column('string', 'Rodic')
    data_table3.new_column('string', 'Tooltip')
    data_table4.new_column('string', 'Nazev a kod')
    data_table4.new_column('string', 'Rodic')
    data_table4.new_column('string', 'Tooltip')
    # Add Rows and Values
    datarows = Array.new
      # Sort projects into tree structure
      Projekt.all.each do |proj|

        onerow = Array.new(3)
        onerow[0] = proj.kod.to_s + ' ' + proj.nazev  #actual node TODO add html graphics

        puts proj.inspect

        if proj.kod.to_s.length == 1
          parent = ''
          puts 'length 1, nazev: ' + proj.nazev + ', parent: ' + parent
        end

        if proj.kod.to_s.length == 3
          tkod = proj.kod.to_s[0,1]
          parent_proj = Projekt.find_by kod: tkod.to_i
          puts 'length 3, nazev: ' + proj.nazev + ', parent proj: ' + parent_proj.inspect
          parent = parent_proj.kod.to_s + ' ' + parent_proj.nazev
        end

        if proj.kod.to_s.length == 4
          tkod = proj.kod.to_s[0,3]
          parent_proj = Projekt.find_by kod: tkod.to_i
          puts 'length 4, nazev: ' + proj.nazev + ', parent proj: ' + parent_proj.inspect
          parent = parent_proj.kod.to_s + ' ' + parent_proj.nazev
        end

          onerow[1] = parent      #parent node
          onerow[2] = proj.nazev  #tooltip
          datarows << onerow
        end

        datarows = datarows.sort

        datarows1 = datarows.select {|row| row[0][0] == '1'}
        datarows2 = datarows.select {|row| row[0][0] == '2'}
        datarows3 = datarows.select {|row| row[0][0] == '3'}
        datarows4 = datarows.select {|row| row[0][0] == '4'}
        data_table1.add_rows(datarows1)
        data_table2.add_rows(datarows2)
        data_table3.add_rows(datarows3)
        data_table4.add_rows(datarows4)

        # puts datarows
        # puts datarows1
        # puts datarows2


    # asdd

    option = { size: 'medium', :allowHtml => true, allowCollapse: true }
    @chart1 = GoogleVisualr::Interactive::OrgChart.new(data_table1, option)
    @chart2 = GoogleVisualr::Interactive::OrgChart.new(data_table2, option)
    @chart3 = GoogleVisualr::Interactive::OrgChart.new(data_table3, option)
    @chart4 = GoogleVisualr::Interactive::OrgChart.new(data_table4, option)
  end
end

app/helpers/prace_polozkas_helper.rb
module PracePolozkasHelper
end

app/views/prace_polozkas/_form.html.erb
<%= form_for(@prace_polozka) do |f| %>
<% if @prace_polozka.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@prace_polozka.errors.count, "error") %> prohibited this prace_polozka from being
    saved:
  </h2>

  <ul>
    <% @prace_polozka.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="col-lg-4"></div>
<div class="col-lg-4">
  <form class="form-horizontal" role="form">
    <div class="form-group">

      <% if @prace_polozka.persisted? %>
      <%= f.select(:osoba_id, @osobas, {include_blank: false}, {class: "form-control", id: 'osoba-sel2'}) %>
      <% else %>
      <%= f.hidden_field :osoba_id, :value => current_user.osoba_id %>
      <% end %>

    </div>
    <div class="form-group center row">
      <%= f.label :projekt_id, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <!-- f.select(:projekt_id, @projekts, {include_blank: true}, {class: "form-control", id: 'sel2'}) -->
        <%= f.select(:projekt_id, @active_projekts, {include_blank: false}, {class: "form-control", id: 'sel2'}) %>

      </div>
    </div>
    <div class="form-group center row">
      <%= f.label :datum, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_field(:datum, :behaviour => 'datepicker', class: 'form-control',
        :value => @prace_polozka.datum.blank? ? Date.today : @prace_polozka.datum) %>
      </div>
    </div>
    <div class="form-group center row">
      <%= f.label :obsah, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_area :obsah, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group center row">
      <%= f.label :hodiny, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.number_field :hodiny, :step => "0.25", :min => "0", class: 'form-control' %>
      </div>
    </div>
    <!--<div class="row padding-top20"></div>-->
    <div class="form-group center actions row ">
      <div class="col-lg-6"></div>
      <%= f.submit 'Uložit', class: 'btn btn-primary col-lg-3 ulozmargin' %>
      <%= link_to 'Zpět', prace_polozkas_path, class: 'btn btn-default col-lg-2 zpetmargin' %>
    </div>
  </div>
</form>

<script type="text/javascript">
  $(document).ready(function () {
    $('[behaviour~=datepicker]').datepicker({
      format: "dd.mm.yyyy",
      weekStart: 1,
      todayBtn: "linked",
      language: "cs",
      todayHighlight: true,
      orientation: "bottom left"
    }
    );
  })

  $(document).ready(function () {
    $("#sel2").select2({
      width: 'resolve'
    }
    );
    $("#osoba-sel2").select2({
      width: 'resolve'
    }
    );
  })
</script>

<% end %>

app/views/prace_polozkas/edit.html.erb
<%= render 'form' %>

app/views/prace_polozkas/index.html.erb
<div class="padding">
	<div class="panel panel-default">
		<div class="panel-bod center">

			<% if signed_in? %>
			<table id="prace_polozkas" class="table table-condensed table-hover table-bordered" style="width:100%">
				<thead>
					<tr>
						<th class="cellaccent"></th>
						<th>Datum</th>
						<th>Jméno</th>
						<th>Práce pro projekt</th>
						<th>Náplň práce</th>
						<th>Počet hodin</th>
						<th></th>
					</tr>
				</thead>

				<tbody>
					<% @prace_polozkas.each do |prace_polozka| %>
						<% os = Osoba.find_by(id: prace_polozka.osoba_id) %>
						<% pr = Projekt.find_by(id: prace_polozka.projekt_id) %>

					<tr>
						<td>
							<% if current_user.osoba_id == 8 or current_user.osoba_id == os.id  %>
								<%= link_to edit_prace_polozka_path(prace_polozka), class: "btn btn-default" do %>
									<%= fa_icon "pencil" %>
								<% end %>
							<% end %>
						</td>						<td><%= prace_polozka.datum %></td>
						<td><%= os.jmeno + " " + os.prijmeni %></td>
						<td><%= pr.kod.to_s + ' - ' + pr.nazev %></td>
						<td><%= prace_polozka.obsah %></td>
						<td><%= prace_polozka.hodiny %></td>
						<td>
							<% if current_user.admin? or current_user.osoba_id == os.id  %>
							<%= link_to prace_polozka, method: :delete, data: { confirm: 'Rozmysli si, Maruško, rozmysli!' }, class: "btn btn-danger" do %>
							<%= fa_icon "trash-o" %>
							<% end %>
						</td>
						<% end %>
					</tr>
					<% end %>

				</tbody>
				<tfoot>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tfoot>
			</table>

			<div class="container">
				<div class="row">
					<% else %>
					<%= link_to "přihlaš se!", signin_path, :class => "btn btn-lg btn-warning" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/prace_polozkas/month_statistika.html.erb
<h1>Info podle měsíců</h1>

<table class="table table-condensed table-hover table-bordered">
  <thead>
    <tr>
      <th>Id</th>
      <th>Osoba</th>
      <th>Hodiny</th>
    </tr>
  </thead>
  <tbody>
    <% @mesicni_hodiny.each do |mh| %>
    <tr>
      <td><%= mh[0] %></td>
      <td><%= mh[1].jmeno + " " + mh[1].prijmeni %></td>
      <td>
        <% mh[2] = mh[2].sort { |x,y| y <=> x } %>
        <% mh[2].each do |mh2| %>
          <strong><%= mh2[0].month.to_s + "/" + mh2[0].year.to_s + ": " %></strong>
          <%= mh2[1] %><br/>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/prace_polozkas/new.html.erb
<%= render 'form' %>

app/views/prace_polozkas/settings.html.erb
<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#uzivatele" aria-controls="uzivatele" role="tab" data-toggle="tab">Správa uživatelů</a></li>
    <li role="presentation"><a href="#projekty" aria-controls="projekty" role="tab" data-toggle="tab">Správa projektů</a></li>
  </ul>


  <div class="tab-content">

    <div role="tabpanel" class="tab-pane active" id="uzivatele">

      <h1>Správa uživatelů</h1>

      <table>
        <thead>
          <tr>
            <th>Aktivní?</th>
            <th>Jméno</th>
          </tr>
        </thead>
        <tbody>

          <% @users.each do |us| %>
          <% os = @osobas.find(us.osoba_id) %>
          <tr>
            <td class="text-center"><input type="checkbox" id=<%= us.id %> name=<%= us.id %> <%= us.active? ? "checked" : "" %> onClick="userToggle(<%= us.id %>)" ></td>
            <td><%= [os.jmeno,os.prijmeni].join(" ") %></td>
          </tr>
          <% end %>

        </tbody>
      </table>
    </div>

    <div role="tabpanel" class="tab-pane" id="projekty">

      <h1>Správa projektů</h1>

      <%= button_to "Nový projekt", action: "new", controller: "projekts" %>

      <table>
        <thead>
          <tr>
            <th>Aktivní?</th>
            <th>Jméno</th>
          </tr>
        </thead>
        <tbody>

          <% @projekts.each do |pr| %>
          <tr>
            <td class="text-center"><input type="checkbox" id=<%= pr.id %> name=<%= pr.id %> <%= pr.active? ? "checked" : "" %> onClick="projectToggle(<%= pr.id %>)" ></td>
            <td><%= [pr.kod, pr.nazev].join(" ") %></td>
          </tr>
          <% end %>

        </tbody>
      </table>


    </div>


  </div>
</div>

app/views/prace_polozkas/show.html.erb
<p id="notice"></p>

<p>
  <strong>Osoba:</strong>
  <%= @prace_polozka.osoba_id %>
</p>

<p>
  <strong>Projekt:</strong>
  <%= @prace_polozka.projekt_id %>
</p>

<p>
  <strong>Datum:</strong>
  <%= @prace_polozka.datum %>
</p>

<p>
  <strong>Obsah:</strong>
  <%= @prace_polozka.obsah %>
</p>

<p>
  <strong>Hodiny:</strong>
  <%= @prace_polozka.hodiny %>
</p>

<%= link_to 'Upravit záznam', edit_prace_polozka_path(@prace_polozka) %> |
<%= link_to 'K výkazu práce', prace_polozkas_path %>

app/views/prace_polozkas/statistika.html.erb
<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#lide" aria-controls="lide" role="tab" data-toggle="tab">Lidé</a></li>
    <li role="presentation"><a href="#projekty" aria-controls="projekty" role="tab" data-toggle="tab">Projekty</a></li>
    <!-- <li role="presentation"><a href="#lidi-projekty" aria-controls="lidi-projekty" role="tab" data-toggle="tab">Lidi - Projekty po měsících</a></li> -->
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="lide">
      <h1>Součty hodin po měsících - lidé</h1>


      <% @months_worked_osobas.reverse_each do |month| %>

      <table class="table table-condensed table-hover table-bordered">
        <thead>
          <tr>
            <th><%= month[0] %></th>
            <!-- <th>Kód projektu</th> -->
            <th>Hodiny</th>
            <th colspan="4">Rozdělení práce na projektech</th>
          </tr>
        </thead>

        <tbody>
          <% month[1].each do |os| %>
          <% thisos = @osobas.find {|a| a.id == os[0]} %>
          <tr id="lidetable-lastrow-left">
            <td rowspan="<%= (os[2].size + 1) %>"><strong><%= thisos.jmeno.to_s + " " + thisos.prijmeni.to_s  %></strong></td>
            <td rowspan="<%= (os[2].size + 1) %>"><%= os[1] %></td>

            <% os[2].each_with_index do |projs, index| %>
            <tr <%= index==(os[2].size-1) ? 'id=lidetable-lastrow-right' : "" %> >
                          <td><%= @projekts.find_by_id(projs[0]).nazev %></td>
                          <td><%= projs[1] %> h</td>
                          <td><%= ((100*projs[1]/os[1]).round(1)) %> %</td>
                          <td><%= ((projs[1]/os[1]).round(1)) %></td>
            </tr>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>

      <% end %>

<!--       <table class="table table-condensed table-hover table-bordered">
        <thead>
          <tr>
            <th>Osoba</th>
            <th>Měsíce</th>
            <th>Hodiny</th>
          </tr>
        </thead>
        <tbody>
          <% @mesicni_hodiny.each do |mh| %>
          <tr>
            <td><%= mh[2].jmeno + " " + mh[2].prijmeni %></td>
            <% mh[3] = mh[3].sort { |x,y| y <=> x } %>
            <% mh[3].each do |mh2| %>
            <td><strong><%= mh2[0].month.to_s + "/" + mh2[0].year.to_s%></strong><br/></td>
            <td><%= mh2[1] %><br/></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    -->



  </div>

  <div role="tabpanel" class="tab-pane" id="projekty">
    <h1>Součty hodin po měsících - projekty</h1>

    <% @months_worked.reverse_each do |month| %>

    <table class="table table-condensed table-hover table-bordered">
      <thead>
        <tr>
          <th><%= month[0] %></th>
          <th>Kód projektu</th>
          <th>Hodiny</th>
        </tr>
      </thead>

      <tbody>
        <% month[1].each do |pr| %>
        <% thisproj = @projekts.find {|a| a.id == pr[0]} %>
        <tr>
          <td><%= thisproj.nazev %></td>
          <td><%= thisproj.kod %></td>
          <td><%= pr[1] %></td>
        </tr>
        <% end %>
      </tbody>
    </table>



    <% end %>


<!--       <table class="table table-condensed table-hover table-bordered">
        <thead>
          <tr>
            <th>Název projektu</th>
            <th>Kód projektu</th>
            <th>Měsíce</th>
            <th>Hodiny</th>
          </tr>
        </thead>
        <tbody>
          <% @projektove_hodiny.each do |mh| %>
          <tr>
            <td><%= mh[1].nazev %></td>
            <td><%= mh[1].kod %></td>
            <% mh[2] = mh[2].sort { |x,y| y <=> x } %>
            <% mh[2].each do |mh2| %>
            <td><strong><%= mh2[0].month.to_s + "/" + mh2[0].year.to_s%></strong><br/></td>
            <td><%= mh2[1] %><br/></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>

    -->
  </div>


</div>

</div>