config/routes.rb
RamusVykaz::Application.routes.draw do
  resources :prace_polozkas
  match '/statistika', to: 'prace_polozkas#statistika', via: 'get'
  match '/settings', to: 'prace_polozkas#settings', via: 'get'
  match '/settings', to: 'prace_polozkas#settings', via: 'post'

  match '/month_statistika', to: 'prace_polozkas#month_statistika', via: 'get'

  resources :osobas

  resources :projekts
  match '/projekts/new', to: 'projekts#new', via: 'post'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root 'prace_polozkas#index'

end

app/models/projekt.rb
class Projekt < ActiveRecord::Base
  has_many :prace_polozkas

  # def sum_by_month(month, year)
  	# sum = 0
  	# return self.prace_polozkas.find(:all)
  	# self.sum(each (projekt.hodiny where datum is month, year)*60) # when changing hodinova mzda also change in prace_polozkas.js.coffee
  # end

end

app/controllers/projekts_controller.rb
class ProjektsController < ApplicationController
  # GET /projekts/new
  def new
    @projekt = Projekt.new
  end

  def create
    @projekt = Projekt.new(projekt_params)

    respond_to do |format|
      if @projekt.save
        format.html { redirect_to action: 'new' } # changed to render index from redirect_to @projekt
        format.json { render action: 'show', status: :created, location: @projekt }
        flash[:notice] = "Záznam byl vytvořen!"
      else
        format.html { render action: 'new' }
        format.json { render json: @projekt.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def projekt_params
    params.require(:projekt).permit(:nazev, :kod, :active)
  end

end

app/helpers/projekts_helper.rb
module ProjektsHelper
end

app/views/projekts/_form.html.erb
<%= form_for(@projekt) do |f| %>
<% if @projekt.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@projekt.errors.count, "error") %> prohibited this projekt from being
    saved:
  </h2>

  <ul>
    <% @projekt.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="col-lg-4"></div>
<div class="col-lg-4">
  <form class="form-horizontal" role="form">

    <div class="form-group center row">
      <%= f.label :nazev, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_field(:nazev, class: 'form-control') %>
      </div>
    </div>
    <div class="form-group center row">
      <%= f.label :kod, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_field :kod, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group center row">
      <%= f.label :active, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.check_box :active, class: 'form-control' %>
      </div>
    </div>
    <!--<div class="row padding-top20"></div>-->
    <div class="form-group center actions row ">
      <div class="col-lg-6"></div>
      <%= f.submit 'Uložit', class: 'btn btn-primary col-lg-3 ulozmargin' %>
      <%= link_to 'Zpět', projekts_path, class: 'btn btn-default col-lg-2 zpetmargin' %>
    </div>
  </div>
</form>


<script type="text/javascript">
  $(document).ready(function () {
  })

  $(document).ready(function () {
    $("#sel2").select2({
      width: 'resolve'
    }
    );
  })
</script>

<% end %>

app/views/projekts/new.html.erb
<%= render 'form' %>