config/routes.rb
RamusVykaz::Application.routes.draw do
  resources :prace_polozkas
  match '/statistika', to: 'prace_polozkas#statistika', via: 'get'
  match '/settings', to: 'prace_polozkas#settings', via: 'get'
  match '/settings', to: 'prace_polozkas#settings', via: 'post'

  match '/month_statistika', to: 'prace_polozkas#month_statistika', via: 'get'

  resources :osobas

  resources :projekts
  match '/projekts/new', to: 'projekts#new', via: 'post'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root 'prace_polozkas#index'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "VÝKAZ PRÁCE", root_path, class: 'h1 navbar-brand' %>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<%= render 'layouts/navigation_links' %>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if signed_in? %>
				<li class="navbar-text">
					<%= Osoba.find_by(id: current_user.osoba_id).jmeno + " " +
					Osoba.find_by(id: current_user.osoba_id).prijmeni %>
				</li>
				<li>
					<%= link_to "odhlaš se!", signout_path, method: "delete", :class => "" %>
				</li>

				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li>
	<div id="novyzapisbtn">
		<% if signed_in? %>
		<%= link_to 'Zapsat hodiny', new_prace_polozka_path, :class => "btn kontrastbtn" %>
		<% end %>
	</div>
</li>

<li>
	<div id="statistika">
		<% if signed_in? %>
		<% if current_user.admin? %>
		<%= link_to 'Statistika', statistika_path, :class => 'btn kontrastbtn' %>
		<% end %>
		<% end %>
	</div>
</li>

<li>
	<div id="statistika po mesicich">
		<% if signed_in? %>
		<% if current_user.osoba_id == 8 %>
		<%= link_to 'month_statistika', month_statistika_path, :class => 'btn kontrastbtn' %>
		<% end %>
		<% end %>
	</div>
</li>

<li>
	<div id="settings">
		<% if signed_in? %>
		<% if current_user.admin? %>
		<%= link_to 'Nastavení', settings_path, :class => 'btn kontrastbtn' %>
		<% end %>
		<% end %>
	</div>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<script src='http://www.google.com/jsapi'></script>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Ramus // Výkaz práce" %></title>
		<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ramus Vykaz" %>">
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body data-no-turbolink>
		<header>
			<%= render 'layouts/navigation' %>
		</header>
		<main role="main">
			<%= render 'layouts/messages' %>
			<%= yield %>
		</main>
	</body>
	<div class="container">
	<footer class="row">
		<section class="col-md-6">Kopyrajt Ramus ajtý sekce</section>
		<section class="col-md-6">Made during a lunch break</section>
	</footer>
	</div>
</html>